### ISSUE TITLE
dtrpg scraper UniCode error?

### ISSUE THREAD

**Issue by bluetyson** [RiotInferno/dungeonScripts#1]
Very first try at setting up and running this linux style, so probably me :-: 

Traceback (most recent call last):
  File "scraper.py", line 48, in <module>
    processData(getUrl(), 1)
  File "scraper.py", line 26, in processData
    [f.write(x['title']+'\n') for x in soup.find('table', class_='productListing').find_all('a', title=True)[3:]]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 21: ordinal not in range(128)

**Comment by RiotInferno** [comment]
@bluetyson What environment are you using?

I found that with windows 10 command prompt, I need to issue the command 

```
chcp 65001
```

to enable better UTF support (as the command promp is ASCII by default)

**Comment by RiotInferno** [comment]
I just re-read your report. That's in the write() not the print().
I'll look at write-encoding options and make sure I have UTF-8 support.

**Comment by bluetyson** [comment]
Cool....yeah, I have looked at encoding etc zero so far.  A Linux Mint flavour.

**Comment by RiotInferno** [comment]
This should be fixed in b15e2e7fe9ad59253265cff83df0561c0ee214d7
Please let me know if this fixes it for you (or not!)

**Comment by bluetyson** [comment]
Tried your update, no joy...so, machine I am running using Python 2.7  are you using 3?  That could be it, as not making much sense not knowing about python otherwise.

**Comment by bluetyson** [comment]
Traceback (most recent call last):
  File "scraper.py", line 49, in <module>
    processData(getUrl(), 1)
  File "scraper.py", line 26, in processData
    with open(getCurrentFile(), 'a', encoding="utf-8") as f:
TypeError: 'encoding' is an invalid keyword argument for this function

as can't see how that would fail otherwise if it works fine for you

**Comment by bluetyson** [comment]
http://stackoverflow.com/questions/27208163/annoying-encoding-issue

In Python 2, the open() function takes no encoding argument. The third argument is the buffering option instead.

You appear to be confused with the Python 3 version. If so use io.open() instead:

import io

with io.open("file1.txt", "a", encoding="utf-8-sig") as f:

In Python 3, the io.open() function replaced the version from Python 2.

**Comment by RiotInferno** [comment]
Yes, this is written in python3.
Your patch looks good, I'll merge it in!
Thanks.
